class AppError {
  message: string;
  statusCode: number;
  constructor(message: string, statusCode = 400) {
    this.message = message;
    this.statusCode = statusCode;
  }
}

export { AppError };
// ESSE CODIGO É UM EXEMPLO DE COMO CRIAR UM ERRO PERSONALIZADO PARA A APLICAÇÃO
// ELE PODE SER USADO PARA GERENCIAR ERROS DE FORMA MAIS EFICAZ, ESPECIALMENTE EM UM CONTEXTO DE API
// ONDE VOCÊ QUER RETORNAR CÓDIGOS DE STATUS HTTP ADEQUADOS E MENSAGENS DE ERRO CLARAS
// ESSE CÓDIGO É ÚTIL PARA MANIPULAR ERROS DE FORMA CONSISTENTE EM TODA A APLICAÇÃO
// VOCÊ PODE LANÇAR UM AppError EM QUALQUER LUGAR DO SEU CÓDIGO E ELE SERÁ CAPTURADO POR UM MIDDLEWARE DE ERRO
